### ISSUE TITLE
overlapping tracks/signals intruduced in commit 18d3b11

### ISSUE THREAD

**Issue by Darthyson** [kvanderlaag/7Up-Extruder-PCB#1]
commit 18d3b11 made the PCB useless by overlapping nearly all tracks/signals.

![Bild1](https://user-images.githubusercontent.com/4217609/213483360-24ceb8b4-a773-459f-8936-e0dcc6e92efd.jpg)

**Comment by kvanderlaag** [comment]
Fixed in https://github.com/kvanderlaag/7Up-Extruder-PCB/commit/35ca0986024968bb7b7bcef41f84c75d00d74ad1 -- moving the connector obviously would have misaligned the existing traces, and since they were sandwiched between pins already, naturally they overlapped.

While this is obviously a silly thing to have missed, I feel like it may benefit you to be slightly more tactful in your phrasing when submitting an issue with a screenshot of the board editor when the fix takes about as long as writing "Commit 18d3b11 made the PCB useless."

**Comment by Darthyson** [comment]
I'm sorry I did not mean to offend you. English is not my first language. Maybe it's an easy fix for you. In eagle i could fix that. KiCad right now i can only use as a viewer. Thanks a lot for your fast response and fix.

**Comment by kvanderlaag** [comment]
Very fair! I probably should have been more considerate of tone in written issues often being a question of translation; I will admit i was slightly cranky because I rolled out of bed to it, so my apologies as well.

To be fair, I have absolutely no idea how to do _anything_ in EAGLE, so you're one ahead of me there. It might be worth converting the board into multiple formats, so people who want to add anything (there's lots of room on that connector that's largely unused right now) can do so easily. EAGLE would be a good candidate.
